[tool.poetry]
name = "devo-mlmodelmanager"
version = "0.2.0"
description = "A client for Devo's ML model manager"
authors = ["Devo ML Team <machine.learning@devo.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "devo_ml"}]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
validators = "^0.20.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
mypy = "^0.971"
types-requests = "^2.28.10"
flake8 = "^5.0.4"
coverage = "^6.4.4"
requests-mock = "^1.10.0"
tox = "^3.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
