# Source: https://coderefinery.github.io/documentation/gh_workflow/
#         and https://glebbahmutov.com/blog/versioned-doc-pages/

# Publish documentation to: https://devoinc.github.io/python-mlmodelmanager-client/
name: Docs

# After bumping version (when closed Pull Requests to main) and tests are passed
on:
  workflow_run:
    workflows: ["Publish Python Package to Pypi"]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'
      - name: Save version
        run: |
          POETRY_VERSION=$(poetry version -s)
          echo "RELEASE_VERSION=S{POETRY_VERSION}"
          echo "RELEASE_VERSION=${POETRY_VERSION}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install sphinx
          pip install sphinx-autodoc-typehints
          pip install furo
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy the current public folder
          # to <base url>/x.y.z version subfolder
          publish_dir: ./_build
          destination_dir: ${{ env.RELEASE_VERSION }}
