name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions
          poetry install --no-interaction
      - name: Run tox
        run: tox
